/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : string,
  'projectType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'budget' : [] | [string],
}
export interface Project {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'area' : string,
  'year' : bigint,
  'conceptDescription' : string,
  'imageIds' : Array<string>,
  'isFeatured' : boolean,
  'isArchive' : boolean,
  'materials' : string,
  'category' : ProjectCategory,
  'sustainabilityHighlights' : string,
  'location' : string,
}
export type ProjectCategory = { 'commercial' : null } |
  { 'institutional' : null } |
  { 'residential' : null } |
  { 'landscape' : null };
export interface TeamMember {
  'id' : string,
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'imageId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addTeamMember' : ActorMethod<[TeamMember], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchProjects' : ActorMethod<[string], Array<Project>>,
  'submitContactInquiry' : ActorMethod<[ContactInquiry], undefined>,
  'updateProject' : ActorMethod<[string, Project], undefined>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];